version: '3.4'

services:
  web:
    image: kentico/ems:web-12.0-beta
    ports:
      - 60051:80
    links:
      - sql
    depends_on:
      - sql    

  sql:
    image: kentico/ems:db-12.0-beta
    ports:
      - 1435:1433