version: '3.4'

services:
  web:
    #build: 
    #    context: .\ems-web-only
    image: kentico/ems:web-12.0.29
    ports:
      - 60051:80
    links:
      - sql
    depends_on:
      - sql    

  sql:
    #build: 
    #    context: .\ems-db
    image: kentico/ems:sql-12.0.29
    ports:
      - 1435:1433