# This image contains a SQL Server Express setup with a Kentico EMS DB installed.

# Iniital setup and configuration of SQL Server Express
FROM microsoft/mssql-server-windows-express AS db
ENV ACCEPT_EULA="Y"
ENV SA_PASSWORD="Pass@word1"

# Copy pre-configured Kentico EMS SQL DB
#FROM db AS final
#WORKDIR /
#COPY ["/update", "c:/Program Files/Microsoft SQL Server/MSSQL14.SQLEXPRESS/MSSQL/data/"]